### PR TITLE
delete temprairy file's

### PR DESCRIPTION
**Pull request by HatsunnyMyku**
files makes mess delete

### CODE REVIEW

**Comment by HatsunnyMyku** [comment]
im gay btw

**Comment by HatsunnyMyku** [comment]
so dont hate :)))))

**Comment by zeroeightysix** [comment]
Hi, thanks for your PR.

Unfortunately I'll have to close this PR because the files you're trying to remove are vital to the build process, or helpful to newcomers.

**Comment by Boundarybreaker** [comment]
This is a throwaway; they did some fucky stuff with Fabric API as well. I've blocked them from the or.g

**Pull request closed without merging**
